<?php require('Resources/Templates/ExampleHeader.phtml'); ?>
	
	<!-- Load Custom Language -->
	<script type="text/javascript" src="Source/Language/Template.mylang.js"></script>
	
	<script type="text/javascript">
		window.addEvent('domready', function(){
			
			var options = {
					language : 'mylang',
					theme: 'enlighter',
					rawButton: true,
					windowButton: true,
					indent : 2,
					infoButton: true,
					showLinenumbers: true
			};
			EnlighterJS.Util.Helper(document.getElements('pre'), Object.merge(options,{
				renderer : 'Block'
			}));
			
			EnlighterJS.Util.Helper(document.getElements('code'), Object.merge(options,{
				renderer : 'Inline'
			}));
	
		});
	</script>
</head>

<body>
	<!-- Begin page content -->
	<div class="container">
		<div class="page-header">
			<h1>
				<strong>EnlighterJS</strong> <small>Language Development</small>
			</h1>
		</div>
		<div id="content">
			<!-- ############################################################# -->
			<div class="well">Start your Language-Development by editing the file <strong>Source/Language/Template.mylang.js</strong> - all changes will directly appear into this document without the need of a rebuild!</div>
			

			<h2>Inline Content</h2>
			<p>
				Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
				<code class="special">if FILE == 123.123 then</code>
				invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.<br /> Lorem ipsum dolor sit amet,
				<code>not highlighted</code>
				consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
			</p>

<h2>HTML Content</h2>
<pre data-enlighter-language="mylang">
&lt;!##
# This is a hash-style-comment
if FILE == 123.123 then
	echo 'testcase'
elseif
	echo "OH NO"	
endif
##!&gt;
</pre>


		
		<!-- ############################################################# -->
		</div>
		<!-- // content -->

	</div>
	<!-- // container -->
</body>
</html>