<section>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-sm-12">
                <article>
                    <?php include('.tmp/Documentation.html'); ?>
                </article>
            </div>

            <div class="col-md-2 hidden-xs hidden-sm">
                <ul id="content-nav" data-autogen="true"></ul>

                <div id="ToTop">
                    <a href="#" class="glyphicon glyphicon-upload" title="Scroll To Top"></a>
                </div>
            </div>
        </div>
    </div>
</section>