<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	
	<!-- Favicon !-->
	<link rel="icon" href="Resources/favicon.png" type="image/png" />
	
	<title>EnlighterJS Playground</title>
	
	<!-- Bootstrap CSS - just 4 styling ;)  -->
	<link rel="stylesheet" href="Resources/bootstrap/bootstrap.min.css" />
    <link href='https://fonts.googleapis.com/css?family=Droid+Sans+Mono' rel='stylesheet' type='text/css'>


	<!-- EnlighterJS Styles -->
<?php 
    require('Util/global.php');

$theme = 'eclipse';

	foreach ($sources->css as $css){
		echo '<link rel="stylesheet" href="', $css, '" />', "\n";
	}
?>
    <link rel="stylesheet" href="Source/Themes/Minimal.css?<?php echo time() ?>" />
	<!-- Include MooTools Framework -->
	<script type="text/javascript" src="Resources/MooTools.min.js"></script>
	

	<script type="text/javascript">
		// attention: don't use load or domready here! the jsloaded event is triggered by DynamicSourcefileLoader
		window.addEvent('domready', function(){
			
			var options = {
					language : 'js',
					theme: 'minimal',
					rawButton: true,
					windowButton: true,
					indent : 2,
					infoButton: true,
					showLinenumbers: true
			};
	
			//document.getElements('pre.special').enlight(options);
	
			//document.id('NoLight').enlight(true).enlight(false);
            console.time('Rendering');
		EnlighterJS.Util.Init('pre', 'code', options);
            console.timeEnd('Rendering');
		/*
			EnlighterJS.Util.Helper(document.getElements('pre.special'), Object.merge(options,{
				renderer : 'Block',
			}));
			
			EnlighterJS.Util.Helper(document.getElements('code.special'), Object.merge(options,{
				renderer : 'Inline',
			}));
	*/

		});
	</script>

    <script type="text/css">




    </script>
</head>

<body>
	<!-- Begin page content -->
	<div class="container">

			<h1>
				<strong>EnlighterJS</strong> <small>Development Playground</small>
			</h1>

		<div id="content">
			<!-- ############################################################# -->

            <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
                <code data-enlighter-language="lua">local a = "Double Quoted\nString"</code> invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.
            </p>

            <?php echo file_get_contents('Resources/TestcaseData/javascript.html'); ?>

		<!-- ############################################################# -->
		</div>
		<!-- // content -->


	</div>
	<!-- // container -->

	<!-- Sticky Footer Message -->
	<div id="footer">
		<div class="container">
			<p class="">
				<strong>EnlighterJS</strong> is developed by <a href="http://andidittrich.de">Andi Dittrich</a><br /> <a href="https://github.com/AndiDittrich/EnlighterJS/archive/master.zip">Download</a> EnlighterJS on <a href="https://github.com/AndiDittrich/EnlighterJS">GitHub</a> | It's released under the Terms of <a href="../LICENSE.md">MIT X11 License</a> | Demo created with <a href="http://getbootstrap.com">Bootstrap</a>
			</p>
		</div>
	</div>
	<!-- // Sticky Footer Message -->

    <!-- EnlighterJS Sourcefiles -->
    <script type="text/javascript">/* <![CDATA[ */
        (function(){
            'use strict';
        <?php
       foreach ($sources->js as $js){
           $x = file_get_contents($js);
           echo preg_replace('#^/\*[\s\S]+\*/#Ui', '', $x);
       }
       ?>
        })();
        /* ]]> */</script>

</body>
</html>