<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	
	<!-- Favicon !-->
	<link rel="icon" href="Resources/favicon.png" type="image/png" />
	
	<title>EnlighterJS Playground</title>
	
	<!-- Bootstrap CSS - just 4 styling ;)  -->
	<link rel="stylesheet" href="Resources/bootstrap.min.css" />
	<link rel="stylesheet" href="Resources/bootstrap-theme.min.css" />
	<link rel="stylesheet" href="Resources/Template.css" />

	<!-- EnlighterJS Styles -->
<?php 
// load js+css source list
$sourceList = json_decode(file_get_contents('Build/Sources.dev.json'));
$jsSources = explode(' ', $sourceList->js);
$cssSources = explode(' ', $sourceList->css);

	foreach ($cssSources as $css){
		echo '<link rel="stylesheet" href="', $css, '" />', "\n";
	}
?>	
	
	<!-- Include MooTools Framework -->
	<script type="text/javascript" src="Resources/mootools-core-1.5.0-full-nocompat-yc.js"></script>
	
	<!-- EnlighterJS Sourcefiles -->
	<?php 
	foreach ($jsSources as $js){
		echo '<script type="text/javascript" src="', $js, '"></script>', "\n";
	}
	?>
	
	<script type="text/javascript">
		// attention: don't use load or domready here! the jsloaded event is triggered by DynamicSourcefileLoader
		window.addEvent('domready', function(){
			
			var options = {
					language : 'js',
					theme: 'beyond',
					rawButton: true,
					windowButton: true,
					indent : 2,
					infoButton: true,
					showLinenumbers: true
			};
	
			//document.getElements('pre.special').enlight(options);
	
			//document.id('NoLight').enlight(true).enlight(false);
		EnlighterJS.Util.Init('pre.special', 'code.special', options);
		/*
			EnlighterJS.Util.Helper(document.getElements('pre.special'), Object.merge(options,{
				renderer : 'Block',
			}));
			
			EnlighterJS.Util.Helper(document.getElements('code.special'), Object.merge(options,{
				renderer : 'Inline',
			}));
	*/
		});
	</script>
</head>

<body>
	<!-- Begin page content -->
	<div class="container">
		<div class="page-header">
			<h1>
				<strong>EnlighterJS</strong> <small>Advanced Javascript Syntax Highlighter</small>
			</h1>
		</div>
		<div id="content">
			<!-- ############################################################# -->

			<h2>Inline Content</h2>
			<p>
				Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
				<code class="special">window.addEvent('domready', function(){});</code>
				invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.<br /> Lorem ipsum dolor sit amet,
				<code>not highlighted</code>
				consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet.
			</p>

<pre class="special" data-enlighter-language="html">
&lt;!DOCTYPE html&gt;
&lt;head&gt;
		&lt;!-- Include EnlighterJS Styles --&gt;
		&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;../Build/EnlighterJS.yui.css&quot; /&gt;
		
		&lt;!-- Include MooTools Framework --&gt;
		&lt;script type=&quot;text/javascript&quot; src=&quot;mootools-core-1.4.5-full-nocompat.js&quot;&gt;&lt;/script&gt;
		
		&lt;!-- Include EnlighterJS --&gt;
		&lt;script type=&quot;text/javascript&quot; src=&quot;../Build/EnlighterJS.yui.js&quot; &gt;&lt;/script&gt;
		
		&lt;!-- Initialize EnlighterJS --&gt; 
		&lt;script type=&quot;text/javascript&quot;&gt;
		window.addEvent('domready', function() {
			// highlight all pre tags
			$$('pre').light({
				altLines : 'hover',
				indent : 2,
				editable: false
			});
		});
		&lt;/script&gt;

&lt;!-- Syntax highlight using Languages/Js.js and default theme --&gt; 
&lt;pre data-enlighter-language=&quot;css&quot;&gt;var myClass = new Class({})&lt;/pre&gt; 
 
&lt;!-- Syntax highlight using Languages/Php.js and theme from Themes/Twilight.css --&gt; 
&lt;pre data-enlighter-language=&quot;php&quot; data-enlighter-theme=&quot;twilight&quot;&gt;&lt;?php php_info() ?&gt;&lt;/pre&gt;

</pre>

	
			<h2>JS Testcode</h2>
			<pre class="special" data-enlighter-group="g1" id="Lightit1" data-enlighter-lineoffset="5" data-enlighter-title="Javascript1" data-enlighter-highlight="10,16-19">
window.addEvent('domready', function(){
	// metadata config available ? -> autoinit
	var m = document.getElement('meta[name="EnlighterJS"]');
	
	// check instance
	if (!m){
		return;
	}
	
	// create new options object
	var options = {
		language: m.get('data-language') || 'generic',
		theme: m.get('data-theme') || 'Enlighter',
		indent: m.get('data-indent').toInt() || -1,
		hover: m.get('data-hover') || 'hoverEnabled'
	};
		
	// selector available ? if not, match all pre-tags
	var blockSelector = m.get('data-selector-block') || 'pre';
	
	// selector available ? if not, match all code-tags
	var inlineSelector = m.get('data-selector-inline') || 'code';
});
	</pre>
	
				<pre class="special" data-enlighter-group="g1" data-enlighter-linenums="true" data-enlighter-title="TypeScript ?!" data-enlighter-theme="mootools">


// create output container element
var container = new Element(this.options.containerTag);

// set class and id attributes.
container.addClass(theme + 'EnlighterJS');		
container.addClass('EnlighterJSRendered');		
container.set('id', 'EnlighterJS_' + String.uniqueID());

// generate output based on ordered list of tokens
language.getTokens().each(function(token, index){
	// get classname
	var className = 		 		   token.type ? (language.aliases[token.type] || token.type) : '';
	
	
	
	
	// create new inline element which contains the token - htmlspecialchars get escaped by mootools setText !
	container.grab(new Element('span', {
		'class': className,
		'text': token.text
	}));
});

return container;
	</pre>
<pre class="special" data-enlighter-group="g1" data-enlighter-linenums="true" data-enlighter-theme="mootools">
// set class and id attributes.
container.addClass(theme + 'EnlighterJS');		
container.addClass('EnlighterJSRendered');		
container.set('id', 'EnlighterJS_' + String.uniqueID());
</pre>
			<h2>No-Highlight</h2>
			<pre data-enlighter-language="no-highlight" data-enlighter-highlight="3,6-9" id="NoLight" class="special">
// create output container element
var container = new Element(this.options.containerTag);

// set class and id attributes.
container.addClass(theme + 'EnlighterJS');		
container.addClass('EnlighterJSRendered');		
container.set('id', 'EnlighterJS_' + String.uniqueID());
</pre>

			<h2>Inline Code</h2>
			<p>
				EnlighterJS also supports
				<code class="special" data-enlighter-language="js">alert('Inline Sourcecode highlighting');</code>
				(since version 1.8).
			</p>
			
			
			
			<h2>Custom Language</h2>
			<pre class="special" data-enlighter-language="mylang">
&lt;!##
# This is a hash-style-comment
if FILE == 123.123 then
	echo 'testcase'
elseif
	echo "OH NO"	
endif
##!&gt;
			</pre>
		<!-- ############################################################# -->
		</div>
		<!-- // content -->


	</div>
	<!-- // container -->

	<!-- Sticky Footer Message -->
	<div id="footer">
		<div class="container">
			<p class="">
				<strong>EnlighterJS</strong> is developed by <a href="http://andidittrich.de">Andi Dittrich</a><br /> <a href="https://github.com/AndiDittrich/EnlighterJS/archive/master.zip">Download</a> EnlighterJS on <a href="https://github.com/AndiDittrich/EnlighterJS">GitHub</a> | It's released under the Terms of <a href="../LICENSE.md">MIT X11 License</a> | Demo created with <a href="http://getbootstrap.com">Bootstrap</a>
			</p>
		</div>
	</div>
	<!-- // Sticky Footer Message -->

</body>
</html>