<!DOCTYPE html>
<html lang="en">
<head>
    <!--
        EnlighterJS Examples

        Author: Andi Dittrich <http://andidittrich.de>
        License: MIT X11 License
     -->

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Favicon !-->
    <link rel="icon" href="Resources/favicon.png" type="image/png" />

    <title>LanguageDevelopment | EnlighterJS</title>

    <!-- Bootstrap CSS - just 4 styling - not required for enlighterjs -->
    <link rel="stylesheet" href="Resources/bootstrap-3.2.0-dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="Resources/bootstrap-3.2.0-dist/css/bootstrap-theme.min.css">

    <!-- Include EnlighterJS Styles -->
    <link rel="stylesheet" type="text/css" href="Build/EnlighterJS.min.css" />

    <!-- Monospace Fonts on Google Webfonts !-->
    <link href='http://fonts.googleapis.com/css?family=Cutive+Mono|Roboto+Mono:400,700,400italic,500,500italic,700italic|Ubuntu+Mono:400,700,400italic,700italic|Droid+Sans+Mono|Source+Code+Pro:400,600' rel='stylesheet' type='text/css'>

    <!-- Include MooTools Framework -->
    <script type="text/javascript" src="Resources/MooTools.min.js"></script>

    <!-- Include EnlighterJS -->
    <script type="text/javascript" src="Build/EnlighterJS.js"></script>
    <script type="text/javascript" src="Source/Tokenizer/Xml.js"></script>
    <script type="text/javascript" src="Source/Language/Xml.js"></script>

	<script type="text/javascript">
		window.addEvent('domready', function(){
			
			var options = {
					language : 'css',
					theme: '',
					rawButton: true,
					windowButton: true,
					indent : 2,
					infoButton: true,
					showLinenumbers: true
			};
			EnlighterJS.Util.Helper(document.getElements('pre'), Object.merge(options,{
				renderer : 'Block'
			}));
			
			/*EnlighterJS.Util.Helper(document.getElements('code'), Object.merge(options,{
				renderer : 'Inline'
			}));*/
	
		});
	</script>
</head>

<body>
	<!-- Begin page content -->
	<div class="container">
		<div class="page-header">
			<h1>
				<strong>EnlighterJS</strong> <small>Language Development</small>
			</h1>
		</div>
		<div id="content">
			<!-- ############################################################# -->
            <?php
            include('Util/global.php');
            include('Resources/Templates/ThemeSelector.phtml');
            ?>
			<div class="well">Start your Language-Development by editing the file <strong>Source/Language/Template.mylang.js</strong> - all changes will directly appear into this document without the need of a rebuild!</div>

            <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor
                <code data-enlighter-language="php">echo 'Arnold once said: "I\'ll be back"';</code> invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet.
            </p>
<pre data-enlighter-language="xml">
&lt;?xml version="1.0" encoding="UTF-8"?&gt;
    &lt;building name="GlobalDynamics Main Building"
    core:id="0xFA8A91C6617DFA1B" core:uid="0898213-123123123-1230898123" xmlns:core="http://www.xmlnamespace.tld"&gt;
	&lt;core:group core:level="2"&gt;
		&lt;room number="123"&gt;Conference Room A&lt;/room&gt;
		&lt;room number="124"&gt;Conference Room B&lt;/room&gt;
		&lt;room number="125"&gt;Conference Room C&lt;/room&gt;
		&lt;room number="126"&gt;Conference Room D&lt;/room&gt;
	&lt;/core:group&gt;
	&lt;core:group core:level="2"&gt;
		&lt;room number="17"&gt;John's Office&lt;/room&gt;
		&lt;room number="19"&gt;Eric's Office&lt;/room&gt;
	&lt;/core:group&gt;
	&lt;core:group core:level="1"&gt;
		&lt;room number="091"&gt;Mainframe Housing A&lt;/room&gt;
		&lt;room number="092"&gt;Mainframe Housing B&lt;/room&gt;
		&lt;room number="090"&gt;Mainframe Power Supply Station&lt;/room&gt;
		&lt;room number="089"&gt;Mainframe Backup Power Supply Station&lt;/room&gt;
	&lt;/core:group&gt;
	&lt;core:group core:level="8"&gt;
		&lt;room number="1717" role="cto"&gt;CTO Office&lt;/room&gt;
		&lt;room number="1819" role="ceo"&gt;CEO Office&lt;/room&gt;
		&lt;room number="1820" role="cfo"&gt;CFO Office&lt;/room&gt;
	&lt;/core:group&gt;
&lt;/building&gt;
</pre>
		
		<!-- ############################################################# -->
		</div>
		<!-- // content -->

	</div>
	<!-- // container -->
</body>
</html>