<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<!-- Favicon !-->
	<link rel="icon" href="<?php echo cdnbase('Resources/favicon.png'); ?>" type="image/png">
	
	<title><?php echo $pageTitle; ?> | EnlighterJS</title>
	
	<!-- Bootstrap CSS - just 4 styling - not required for enlighterjs -->
	<link rel="stylesheet" href="<?php echo cdnbase('Resources/bootstrap.min.css'); ?>">
	<link rel="stylesheet" href="<?php echo cdnbase('Resources/bootstrap-theme.min.css'); ?>">
	<link rel="stylesheet" href="<?php echo cdnbase('Resources/Template.css'); ?>">

	<!-- Include EnlighterJS Styles -->
	<link rel="stylesheet" type="text/css" href="<?php echo cdnbase('Build/EnlighterJS.yui.css'); ?>" />
	
	<!-- Include MooTools Framework -->
	<script type="text/javascript" src="<?php echo cdnbase('Resources/mootools-core-1.4.5-full-nocompat.js'); ?>"></script>

	<!-- Include EnlighterJS -->
	<script type="text/javascript" src="<?php echo cdnbase('Build/EnlighterJS.yui.js'); ?>"></script>	

	<?php echo $headerContent; ?>
</head>
<body>
	<!-- Topnav -->
	<div id="navbar-wrapper">
		<div class="container">
			<div class="navbar navbar-inverse" role="navigation">
				<div class="navbar-header">
					<a class="navbar-brand" href="index.html">EnlighterJS <?php echo ENLIGHTERJS_VERSION ?></a>
				</div>
				<ul class="nav navbar-nav">
					<li><a href="Quickstart.html">Quickstart</a></li>
					<li><a href="index.html">Docs<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="index.html">Documentation</a></li>
							<li><a href="Changelog.html">Changelog</a></li>
						</ul>
					</li>
					<li class="dropdown"><a href="#">Examples<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li class="dropdown-header">Languages</li>
							<li><a href="html.html">HTML</a></li>
							<li><a href="css.html">CSS</a></li>
							<li><a href="js.html">Javascript</a></li>
							<li><a href="xml.html">XML</a></li>
							<li><a href="markdown.html">Markdown</a></li>
							<li><a href="json.html">JSON</a></li>
							<li><a href="php.html">PHP</a></li>
							<li><a href="sql.html">SQL</a></li>
							<li><a href="java.html">Java</a></li>
							<li><a href="python.html">Python</a></li>
							<li><a href="cpp.html">C++</a></li>
							<li><a href="csharp.html">C#</a></li>
							<li><a href="c.html">C</a></li>
							<li><a href="ruby.html">Ruby</a></li>
							<li><a href="nsis.html">NSIS</a></li>
							<li><a href="raw.html">RAW Code</a></li>
							<li><a href="nohighlight.html">No-Highlighted Code</a></li>
							
							<li class="divider"></li>
							<li class="dropdown-header">Special</li>
							<li><a href="unit.html">Unit Testcases</a></li>
						</ul></li>
					<li><a href="Themes.html">Themes</a></li>
					
					<li><a href="http://wordpress.org/plugins/enlighter/">Plugins<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="http://wordpress.org/plugins/enlighter/">Enlighter for WordPress</a></li>
						</ul>
					</li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li><a href="https://github.com/AndiDittrich/EnlighterJS/archive/master.zip">Get EnlighterJS<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li class="dropdown-header">Get it from GitHub</li>
							<li><a href="https://github.com/AndiDittrich/EnlighterJS/archive/master.zip">Download (latest)</a></li>
							<li><a href="https://github.com/AndiDittrich/EnlighterJS">Browse on GitHub</a></li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>
	<!-- // topnav -->


	<!-- Begin page content -->
	<div class="container">
		<div class="page-header">
			<h1>
				<strong>EnlighterJS</strong> <small><?php echo $pageTitle; ?></small>
			</h1>
		</div>
		<div id="content">
			<!-- ############################################################# -->
			<?php echo $pageContent; ?>
			<!-- ############################################################# -->

		</div>
		<!-- // content -->


	</div>
	<!-- // container -->

	<!-- Sticky Footer Message -->
	<div id="footer">
		<div class="container">
			<p class="text-muted">
				<strong>EnlighterJS</strong> is developed by <a href="http://andidittrich.de">Andi Dittrich</a><br /> <a href="https://github.com/AndiDittrich/EnlighterJS/archive/master.zip">Download</a> EnlighterJS on <a href="https://github.com/AndiDittrich/EnlighterJS">GitHub</a> | It's released under the Terms of <a href="LICENSE.txt">MIT X11 License</a> | Demo created with <a href="http://getbootstrap.com">Bootstrap</a>
			</p>
		</div>
	</div>
	<!-- // Sticky Footer Message -->

</body>
</html>