<p>
	You can generate your customized EnlighterJS Builds by using the <a title="Promethium" href="http://promethium.andidittrich.de/">Promethium CloudBuilder</a>. Maybe you don't need all Theme/Languages and you want to strip down the package. The Builder always uses the latest EnlighterJS release and automatically compresses the files using the <a href="http://yui.github.io/yuicompressor/">YUI Compressor</a> (both compressed & uncompessed builds are included!).<br /> No Sourcefiles are included.
</p>

<form method="post" action="http://promethium.andidittrich.de/enlighterjs/">
	<h3>Include Language Support</h3>
	<div class="form-group">
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Cpp]">"Cpp/C" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[CSharp]">"C#" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Css]">"Css" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Java]">"Java" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Js]">"Javascript" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Markdown]">"Markdown" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Nsis]">"NSIS" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Php]">"PHP" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Python]">"Python" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[RAW]">"RAW" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Ruby]">"Ruby" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Shell]">"Shell/Bash" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Sql]">"SQL" Language</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Language[Xml]">"XML/HTML" Language</label>
		</div>
	</div>

	<h3>Include Themes</h3>
	<div class="form-group">
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Theme[Enlighter]">"Enlighter" Theme</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Theme[Git]">"Git" Theme</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Theme[MooTools]">"MooTools" Theme</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Theme[Mocha]">"Mocha" Theme</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Theme[Panic]">"Panic" Theme</label>
		</div>
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Theme[Tutti]">"Tutti" Theme</label>
		</div>						
		<div class="checkbox">
			<label><input value="1" type="checkbox" name="Theme[Twilight]">"Twilight" Theme</label>
		</div>
	</div>
	
	<h3>Special Features</h3>
	<div class="form-group">
		<div class="checkbox">
			<label><input value="1"  type="checkbox" name="Feature[Metainit]">Include the Metainit Utility for easy initialization</label>
		</div>
	</div>	
	
	<br />
	<p>
		<small>The build-process may tke a few seconds</small>
	</p>
	<hr />
	<button class="btn btn-primary btn-lg" type="submit">Download Custom Build</button>
</form>