<!DOCTYPE html>
<html lang="en">
<head>
	<!--
		EnlighterJS Syntax Highlighter
		Author: Andi Dittrich <http://andidittrich.de>
		Version: <?php echo EJS_VERSION; ?>
		License: MIT X11 License
	 -->

	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

    <title><?php echo $title; ?></title>
    <link rel="icon" href="favicon.png" type="image/png">
    <link rel="stylesheet" href="/EnlighterWeb.min.css">
    <link rel="stylesheet" type="text/css" href="/EnlighterJS.min.css?<?php echo EJS_VERSION; ?>" />
    <link href='//fonts.googleapis.com/css?family=Cutive+Mono|Roboto+Mono:400,700,400italic,500,500italic,700italic|Ubuntu+Mono:400,700,400italic,700italic|Droid+Sans+Mono|Source+Code+Pro:400,600|Inconsolata:400,700' rel='stylesheet' type='text/css'>
    <script type="text/javascript" src="/MooTools.min.js?<?php echo EJS_VERSION; ?>"></script>
    <meta name="EnlighterJS" content="Advanced javascript based syntax highlighting" data-theme="enlighter" data-language="generic" data-indent="2" data-selector-block="pre" data-selector-inline="code[data-enlighter-language]" data-rawcodebutton="true" data-windowbutton="true" data-infobutton="true" />
</head>
<body id="EnlighterJS_Web">

    <nav class="topnav" id="top">
        <div class="container">
            <ul class="nav">
                <li><a href="//enlighterjs.org"><span class="glyphicon glyphicon-home"></span>Getting Started</a></li>
                <li><a href="/Documentation.html"><span class="glyphicon glyphicon-file"></span>Documentation</a></li>
                <li><a href="/Language.Javascript.html"><span class="glyphicon glyphicon-flash"></span>Languages</a></li>
                <li><a href="/Theme.Enlighter.html"><span class="glyphicon glyphicon-pencil"></span>Themes</a></li>
                <li><a href="/Plugins.html"><span class="glyphicon glyphicon-plus"></span>Plugins</a></li>
                <li class="pull-right"><a href="https://github.com/EnlighterJS/EnlighterJS/releases/latest"><span class=" glyphicon glyphicon-download-alt"></span>Get It</a></li>
            </ul>

        </div>
    </nav>

    <header>
        <div class="container">
            <h1><?php echo $title; ?></h1>
            <p class="lead"><?php echo $subtitle; ?></p>
        </div>
    </header>

    <div id="ReleaseNotifier">
        <div class="container">
            <p>EnlighterJS v<?php echo EJS_VERSION; ?> is out including new Languages & Themes. <a href="/Changelog.html">View the Changelog</a></p>
        </div>
    </div>

    <?php include($PAGE); ?>

    <footer>
        <div class="container">

            <p class="text-muted">
                <strong class="lead">EnlighterJS</strong> is developed by <a href="https://andidittrich.de">Andi Dittrich</a>
            </p>

            <p id="ghb"></p>

            <p class="text-muted">
            It's released under the Terms of <a href="/LICENSE.txt">The MIT License (X11)</a><br />
            Page created with <span class="glyphicon glyphicon-hand-right"></span> <a href="http://getbootstrap.com">Bootstrap</a> and driven by the power of <span class="glyphicon glyphicon-wrench"></span> <a href="http://mootools.net">MooTools</a>
            | <span class=" glyphicon glyphicon-heart"></span> <a href="http://glyphicons.com/">Glyhpicons</a>
            | <span class="glyphicon glyphicon-paperclip"></span> <a href="http://lesscss.org/">LESS</a  >
            | <span class="glyphicon glyphicon-th-large"></span> <a href="http://github-buttons.andidittrich.de/">Unofficial GitHub Buttons</a>
            </p>

            <p class="text-muted footer-links"><span>Current Tag v<?php echo EJS_VERSION; ?></span>
                | <a href="<?php echo EJS_PACKAGE_ZIP; ?>">Download</a>
                | <a href="https://github.com/EnlighterJS/EnlighterJS/releases">Releases</a>
                | <a href="/Builder.html">Custom Packages</a>
                | <a href="/Changelog.html">Changelog</a>
                | <a href="https://github.com/EnlighterJS/EnlighterJS/issues">Issues</a>
                | <a href="https://github.com/EnlighterJS/EnlighterJS/issues">Feature Request</a>
            </p>
        </div>
        </footer>

    <div id="beyond_corporate_credits">
        <div class="container">
            <div class="row">
                <div class="col-xs-6"><a href="http://andidittrich.de/"><span class="slogan">Beyond Technology</span><br /><small>beyond the visible world</small></a></div>
                <div class="col-xs-6 text-right small"><a href="http://andidittrich.de/privacy_protection.html">Privacy Protection</a> | <a href="http://andidittrich.de/contact.html">Contact</a> | <a href="http://andidittrich.de/imprint.html">Imprint</a></div>
            </div>
        </div>
    </div>

    <script type="text/javascript" src="//api.andidittrich.com/social.js"></script>
    <script type="text/javascript" src="/EnlighterJS.min.js?<?php echo EJS_VERSION; ?>"></script>
    <script type="text/javascript" src="/EnlighterWeb.min.js?<?php echo EJS_VERSION; ?>"></script>

</body>
</html>