<!DOCTYPE html>
<html lang="en">
<head>
    <!--
        EnlighterJS Examples

        Author: Andi Dittrich <http://andidittrich.de>
        License: MIT X11 License
     -->

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <!-- Favicon !-->
    <link rel="icon" href="<?php echo cdnbase('Resources/favicon.png'); ?>" type="image/png" />

    <title><?php echo strip_tags($pageTitle); ?> | EnlighterJS</title>

    <!-- Bootstrap CSS - just 4 styling - not required for enlighterjs -->
    <link rel="stylesheet" href="<?php echo cdnbase('Resources/bootstrap-3.2.0-dist/css/bootstrap.min.css'); ?>">
    <link rel="stylesheet" href="<?php echo cdnbase('Resources/bootstrap-3.2.0-dist/css/bootstrap-theme.min.css'); ?>">

    <!-- Include EnlighterJS Styles -->
    <link rel="stylesheet" type="text/css" href="<?php echo cdnbase('Build/EnlighterJS.min.css'); ?>" />

    <!-- Include MooTools Framework -->
    <script type="text/javascript" src="<?php echo cdnbase('Resources/MooTools-More-1.5.1-compressed.js'); ?>"></script>

    <!-- Include EnlighterJS -->
    <script type="text/javascript" src="<?php echo cdnbase('Build/EnlighterJS.min.js'); ?>"></script>
