<?php require('ExampleHeader.phtml'); ?>
	
	<!-- Initialize EnlighterJS -->
	<meta name="EnlighterJS" content="Advanced javascript based syntax highlighting" data-language="javascript" data-indent="2" data-selector-block="pre" data-selector-inline="code" />
<body>
	<!-- Begin page content -->
	<div class="container">
		<div class="page-header">
			<h1>
				<?php echo $pageTitle; ?>
			</h1>
		</div>
		<div id="content">
		<!-- ############################################################# -->
			<?php echo $pageContent; ?>
		<!-- ############################################################# -->
		</div>
		<!-- // content -->

	</div>
	<!-- // container -->
</body>
</html>