<!DOCTYPE html>
<html lang="en">
<head>
	<!-- 
		EnlighterJS Examples
		
		Author: Andi Dittrich <http://andidittrich.de>
		License: MIT X11 License
	 -->

	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	
	<!-- Favicon !-->
	<link rel="icon" href="Resources/favicon.png" type="image/png" />
	
	<title><?php echo strip_tags($pageTitle); ?> | EnlighterJS Example</title>
	
	<!-- Bootstrap CSS - just 4 styling - not required for enlighterjs -->
	<link rel="stylesheet" href="<?php echo cdnbase('Resources/bootstrap.min.css'); ?>">
	<link rel="stylesheet" href="<?php echo cdnbase('Resources/bootstrap-theme.min.css'); ?>">

	<!-- Include EnlighterJS Styles -->
	<link rel="stylesheet" type="text/css" href="<?php echo cdnbase('Build/EnlighterJS.yui.css'); ?>" />
	
	<!-- Include MooTools Framework -->
	<script type="text/javascript" src="<?php echo cdnbase('Resources/mootools-core-1.5.0-full-nocompat-yc.js'); ?>"></script>
	<script type="text/javascript" src="<?php echo cdnbase('Resources/mootools-more-1.5.0-yc.js'); ?>"></script>
	
	<!-- Include EnlighterJS -->
	<script type="text/javascript" src="<?php echo cdnbase('Build/EnlighterJS.yui.js'); ?>"></script>
	
	<!-- Initialize EnlighterJS -->
	<meta name="EnlighterJS" content="Advanced javascript based syntax highlighting" data-language="javascript" data-indent="2" data-selector-block="pre" data-selector-inline="code" />
<body>
	<!-- Begin page content -->
	<div class="container">
		<div class="page-header">
			<h1>
				<?php echo $pageTitle; ?>
			</h1>
		</div>
		<div id="content">
		<!-- ############################################################# -->
			<?php echo $pageContent; ?>
		<!-- ############################################################# -->
		</div>
		<!-- // content -->

	</div>
	<!-- // container -->
</body>
</html>