<!DOCTYPE html>
<html lang="en">
<head>
	<!-- 
		EnlighterJS
		
		Author: Andi Dittrich <http://andidittrich.de>
		Version: <?php echo ENLIGHTERJS_VERSION ?>
		License: MIT X11 License
	 -->
	 
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	
	<!-- Favicon !-->
	<link rel="icon" href="<?php echo cdnbase('Resources/favicon.png'); ?>" type="image/png">
	
	<title>EnlighterJS - Advanced Javascript based Syntax Highlighter for MooTools</title>
	
	<!-- Bootstrap CSS - just 4 styling - not required for enlighterjs -->
	<link rel="stylesheet" href="<?php echo cdnbase('Resources/bootstrap-3.2.0-dist/css/bootstrap.min.css'); ?>">
	<link rel="stylesheet" href="<?php echo cdnbase('Resources/bootstrap-3.2.0-dist/css/bootstrap-theme.min.css'); ?>">
	<link rel="stylesheet" href="<?php echo cdnbase('Resources/Template.css'); ?>">
	<link rel="stylesheet" href="<?php echo cdnbase('Resources/GitHubButtons.yui.css'); ?>">

	<!-- Include EnlighterJS Styles -->
	<link rel="stylesheet" type="text/css" href="<?php echo cdnbase('Build/EnlighterJS.min.css'); ?>" />
	
	<!-- Include MooTools Framework -->
	<script type="text/javascript" src="<?php echo cdnbase('Resources/MooTools-More-1.5.1-compressed.js'); ?>"></script>
	
	<!-- Some GitHub related stuff -->
	<script type="text/javascript" src="<?php echo cdnbase('Resources/GitHubButtons.MooTools.yui.js'); ?>"></script>
	
	<!-- Include EnlighterJS -->
	<script type="text/javascript" src="<?php echo cdnbase('Build/EnlighterJS.min.js'); ?>"></script>
	
	<!-- Template JS -->
	<script type="text/javascript" src="<?php echo cdnbase('Resources/Template.js'); ?>"></script>
	
	<!-- EnlighterJS Init -->
	<meta name="EnlighterJS" content="Advanced javascript based syntax highlighting" data-language="generic" data-indent="2" data-selector-block="pre" data-selector-inline="code" data-rawcodebutton="true" data-windowbutton="true" data-infobutton="true" />
</head>
<body id="frontpage">
	<?php require('Navigation.phtml'); ?>
	
	 <!-- Carousel
    ================================================== -->
	<div id="frontpageCarousel" class="carousel slide" data-ride="carousel">
		<!-- Indicators -->
		<ol class="carousel-indicators"></ol>
		<div class="carousel-inner">
			<div class="item active">
				<img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="First slide">
				<div class="container">
					<div class="carousel-caption">
						<h1>EnlighterJS Syntax Highlighter</h1>
						<p>A free, easy-to-use, syntax highlighting plugin developed for MooTools.</p>
						<p>
							<a class="btn btn-lg btn-primary" href="https://github.com/AndiDittrich/EnlighterJS/archive/master.zip" role="button">Download EnlighterJS</a>
						</p>
					</div>
				</div>
			</div>
			<div class="item">
				<img src="data:image/gif;base64,R0lGODlhAQABAIAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
				<div class="container">
					<div class="carousel-caption">
						<h1>Build in support for various Languages</h1>
						<p>HTML, CSS, XML, Javascript, Java, Markdown, PHP, Python, Ruby, Shellscript, C, C++, C#, SQL, NSIS</p>
						<p>
							<a class="btn btn-lg btn-primary" href="Documentation.html" role="button">Learn more</a>
						</p>
					</div>
				</div>
			</div>
			<div class="item">
				<img src="data:image/gif;base64,R0lGODlhAQABAIAAAFVVVQAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
				<div class="container">
					<div class="carousel-caption">
						<h1>It's OpenSource! You're Welcome to contribute</h1>
						<p>Got a problem ? Need some special features ? Open an issue on GitHub or pull some code!</p>
						<p>
							<a class="btn btn-lg btn-primary" href="https://github.com/AndiDittrich/EnlighterJS" role="button">Contribute</a>
						</p>
					</div>
				</div>
			</div>
			<div class="item">
				<img src="data:image/gif;base64,R0lGODlhAQABAIAAAGZmZgAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Second slide">
				<div class="container">
					<div class="carousel-caption">
						<h1>High-Quality, CSS based Themes</h1>
						<p>Modify the default Themes or add your own one - everything is based on a simple set of css rules</p>
						<p>
							<a class="btn btn-lg btn-primary" href="Themes.html" role="button">Theme Browser</a>
						</p>
					</div>
				</div>
			</div>
			<div class="item">
				<img src="data:image/gif;base64,R0lGODlhAQABAIAAAFVVVQAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" alt="Third slide">
				<div class="container">
					<div class="carousel-caption">
						<h1>Extensible Language parsing Engine</h1>
						<p>Need support for another language ? Take a look into the LanguageDevelopment tutorial!</p>
						<p>
							<a class="btn btn-lg btn-primary" href="LanguageDevelopment.html" role="button">Language Development</a>
						</p>
					</div>
				</div>
			</div>
		</div>
		<a class="left carousel-control" href="#" role="button" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#" role="button" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
	</div>
	<!-- /.carousel -->

	<!-- START THE FEATURETTES -->
	<div class="container">

		<div class="row featurette">
			<div class="col-md-7">
				<h2 class="featurette-heading">
					ALL-IN-ONE <span class="text-muted">Syntax Highlighting</span>
				</h2>
				<p class="lead">EnlighterJS is a free, easy-to-use, syntax highlighting plugin developed for MooTools. It is based on the famous Lighter.js. Using it can be as simple as adding a single script and style to your website, choosing the elements you wish to highlight, and EnlighterJS takes care of the rest!</p>
				<p>
					<a class="btn btn-lg btn-primary" href="Quickstart.html" role="button">Quickstart</a>
				</p>
			</div>
			<div class="col-md-5">
				<img class="featurette-image img-responsive" src="Resources/img/screenshot-1.jpg" alt="Enlighter Theme" />
			</div>
		</div>

		<hr class="featurette-divider">

		<div class="row featurette">
			<div class="col-md-5">
				<img class="featurette-image img-responsive" src="Resources/img/screenshot-includes.jpg" alt="Required Files" />
			</div>
			<div class="col-md-7">
				<h2 class="featurette-heading">
					Easy to use! <span class="text-muted">Add MooTools & 2 Files</span>
				</h2>
				<p class="lead">
					1. Include MooTools.Core, EnlighterJS Script+Styles into your page <br /> 2. Prepare your sourcecode elements by adding a language identifier<br /> 3. "Initialize" EnlighterJS to highlight the code
				</p>
				<p>
					<a class="btn btn-lg btn-primary" href="Examples/Example1.html" role="button">Startup: Example1</a>
				</p>
			</div>
		</div>

		<hr class="featurette-divider">

		<div class="row featurette">
			<div class="col-md-7">
				<h2 class="featurette-heading">
					WordPress Fanatic? <span class="text-muted">The Official Plugin</span>
				</h2>
				<p class="lead">
					Enlighter - The most simple way to use EnlighterJS. <br /> Full Visual-Editor-Integration. Build-in Theme Customizer. <br />Ready-to-use, Ready-to-post!
				</p>
				<p>
					<a class="btn btn-lg btn-primary" href="http://wordpress.org/plugins/enlighter/" role="button">Enlighter Plugin</a>
				</p>
			</div>
			<div class="col-md-5">
				<img class="featurette-image img-responsive" src="Resources/img/screenshot-2.jpg" alt="WordPress Visual Editor Integration" />
			</div>
		</div>

		<hr class="featurette-divider">

		<div class="row featurette">
			<div class="col-md-5">
				<img class="featurette-image img-responsive" src="Resources/img/screenshot-8.jpg" alt="Required Files" />
			</div>
			<div class="col-md-7">
				<h2 class="featurette-heading">
					Theme Customizer <span class="text-muted">within the WordPress Plugin</span>
				</h2>
				<p class="lead">An easy to use Theme-Customizer is included to modify the build-in themes without any css knowlegde!</p>
				<p>
					<a class="btn btn-lg btn-primary" href="http://wordpress.org/plugins/enlighter/" role="button">Enlighter Plugin</a>
				</p>
			</div>
		</div>

		<hr class="featurette-divider">
		
		<div class="row featurette">
			<div class="col-md-7">
				<h2 class="featurette-heading">
					Tons of Features <span class="text-muted">Innovative & Customizable</span>
				</h2>
				<p class="lead">
				Written in MooTools. Requires version 1.4+<br />
				Inline and Block Syntax highlighting<br />
				Build-in support for various languages<br />
				Extensible language and theme engines<br />
				Simple CSS based themes<br />
				Small footprint: 56kB js + 35kB css<br />
				Toolbar buttons<br />
				Metatag Initialization<br />
				Web-based Customizer
				</p>
				<p>
					<a class="btn btn-lg btn-primary" href="Builder.html" role="button">Customize EnlighterJS</a>
				</p>		
			</div>
			<div class="col-md-5">
				<img class="featurette-image img-responsive" src="Resources/img/screenshot-3.jpg" alt="Required Files" />
			</div>			
		</div>

		<hr class="featurette-divider">

		<!-- /END THE FEATURETTES -->
	</div> 

   <?php require('Footer.phtml'); ?>

</body>
</html>