
<!-- Topnav -->
<div id="navbar-wrapper">
	<div class="navbar navbar-inverse" role="navigation">
		<div class="container">
			<div class="navbar-header">
				<a class="navbar-brand" href="index.html">EnlighterJS <small><?php echo ENLIGHTERJS_VERSION ?></small></a>
			</div>
			<ul class="nav navbar-nav">
				<li><a href="Quickstart.html">Quickstart<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li class="dropdown-header">Startup</li>
						<li><a href="Quickstart.html">Quickstart</a></li>
						<li class="divider"></li>
						<li class="dropdown-header">Examples</li>
						<li><a href="Examples/Example1.html" target="_blank">Startup Example</a></li>
						<li><a href="Examples/Example2-jsinit.html" target="_blank">Javascript-Initialization</a></li>
						<li><a href="Examples/Example3-advanced.html" target="_blank">Advanced-Usage</a></li>
					</ul></li>
				<li><a href="Documentation.html">Docs<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="Documentation.html">Documentation</a></li>
						<li><a href="Changelog.html">Changelog</a></li>
					</ul></li>
				<li class="dropdown"><a href="#">Examples<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li class="dropdown-header">Languages</li>
						<li><a href="html.html">HTML</a></li>
						<li><a href="css.html">CSS</a></li>
						<li><a href="javascript.html">Javascript</a></li>
						<li><a href="xml.html">XML</a></li>
						<li><a href="markdown.html">Markdown</a></li>
						<li><a href="json.html">JSON</a></li>
						<li><a href="php.html">PHP</a></li>
						<li><a href="sql.html">SQL</a></li>
						<li><a href="java.html">Java</a></li>
						<li><a href="python.html">Python</a></li>
						<li><a href="cpp.html">C++</a></li>
						<li><a href="csharp.html">C#</a></li>
						<li><a href="c.html">C</a></li>
						<li><a href="ruby.html">Ruby</a></li>
						<li><a href="nsis.html">NSIS</a></li>
						<li><a href="diff.html">Diff</a></li>
                        <li><a href="ini.html">Ini/Conf</a></li>
                        <li><a href="avrasm.html">AVR Assembler</a></li>
						<li><a href="raw.html">RAW Code</a></li>
						<li><a href="nohighlight.html">No-Highlighted Code</a></li>

						<li class="divider"></li>
						<li class="dropdown-header">Special</li>
						<li><a href="unit.html">Unit Testcases</a></li>
					</ul></li>
				<li><a href="Themes.html">Themes</a></li>

				<li><a href="http://wordpress.org/plugins/enlighter/">Plugins<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li><a href="http://wordpress.org/plugins/enlighter/">Enlighter for WordPress</a></li>
					</ul></li>

				<li><a href="https://github.com/AndiDittrich/EnlighterJS/archive/master.zip">Download<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li class="dropdown-header">Special</li>
						<li><a href="Builder.html">Custom EnlighterJS Build</a></li>
						<li class="divider"></li>
						<li class="dropdown-header">Get it from GitHub</li>
						<li><a href="https://github.com/AndiDittrich/EnlighterJS/archive/master.zip">Download Package (latest)</a></li>
						<li><a href="https://github.com/AndiDittrich/EnlighterJS">Browse on GitHub</a></li>
					</ul></li>
					
				<li><a href="#">Help<b class="caret"></b></a>
					<ul class="dropdown-menu">
						<li class="dropdown-header">EnlighterJS Support</li>
						<li><a href="https://github.com/AndiDittrich/EnlighterJS/issues">Report a Bug</a></li>
						<li><a href="https://github.com/AndiDittrich/EnlighterJS/issues">Feature Request</a></li>
						<li><a href="http://andidittrich.de/contact">Contact</a></li>
					</ul></li>	
			</ul>
			<div class="navbar-header navbar-right" id="githubbutton1"></div>
			<div class="navbar-header navbar-right" id="githubbutton2"></div>
		</div>
	</div>

</div>
<!-- // topnav -->