<div class="well">
<p><strong>Welcome to EnlighterJS</strong> - to start with it, follow these simple steps:</p>
<ol>
	<li>Download EnlighterJS and Include the files</li>
	<li>Prepare your sourcecode</li>
	<li>Initialize EnlighterJS</li>
</ol>
</div>

<h3>1. Download & Include EnlighterJS files</h3>
<p>Download EnlighterJS and extract the files. You will find some examples located in the *Examples/* directory. Copy the prebuild files of the *Build/* directory into a web-accessible directory of your choice.</p>
<pre class="EnlighterJS" data-enlighter-language="HTML">&lt;head&gt;
...
&lt;!-- Include EnlighterJS Styles --&gt;
&lt;link rel=&quot;stylesheet&quot; type=&quot;text/css&quot; href=&quot;css/EnlighterJS.yui.css&quot; /&gt;
	 
&lt;!-- Include MooTools Framework --&gt;
&lt;script type=&quot;text/javascript&quot; src=&quot;js/mootools-core-1.4.5-full-nocompat.js&quot;&gt;&lt;/script&gt;

&lt;!-- Include EnlighterJS --&gt;
&lt;script type=&quot;text/javascript&quot; src=&quot;js/EnlighterJS.yui.js&quot; &gt;&lt;/script&gt;
...
&lt;/head&gt;
</pre>


<h3>2. Prepare your sourcecode</h3>
<p>Starting with just a small piece of javascript code you wish to highlight. Prepare your sourcecode by giving the element (containing the code) an optional <code>data-enlighter-language</code> attribute with the language of the snippet.</p>
<pre data-enlighter-language="html">
&lt;pre data-enlighter-language=&quot;js&quot;&gt;
$('#loading-example-btn').click(function () {
	var btn = $(this)
	btn.button('loading')
	$.ajax(...).always(function () {
		btn.button('reset')
	});
});
&lt;/pre&gt;
</pre>


<h3>3. Initialize it!</h3>
<p>The most simple and elegant way to use EnlighterJS on your page: just add a simple <strong>HTML-Meta-Tag</strong> to your page with the desired global config </p>
<pre class="EnlighterJS" data-enlighter-language="HTML">&lt;!-- Initialize EnlighterJS --&gt;	
&lt;meta name=&quot;EnlighterJS&quot; content=&quot;Advanced javascript based syntax highlighting&quot; data-indent=&quot;4&quot; data-selector-block=&quot;pre&quot; data-selector-inline=&quot;code&quot; data-language=&quot;javascript&quot; /&gt;
</pre>

<hr />

<h2>Ready to use Examples!</h2>
<p>Your instantaneous launch into the world of EnlighterJS. For further information, please refer to the <a href="Documentation.html">Documentation</a>.</p>

<h3>Quickstart.html <small><a href="Example1.html">View file</a></small></h3>
<p>The following code provides a minimalistic example how to use EnlighterJS on your page, using the <strong>Metainit</strong> initialization method. This will be the best choice for most users.<br />
Metainit just invokes <code>EnlighterJS.Util.Helper()</code> on <code>domready</code> using metatag attributes as options.</p>

<pre data-enlighter-language="html" data-enlighter-lineoffset="24">
<?php echo htmlspecialchars(extractContent('Example1.html', 24, 36), ENT_HTML5); ?>
</pre>

<h3>Quickstart-jsinit.html - Javascript Initialization <small><a href="Example2-jsinit.html">View file</a></small></h3>
<p>In some cases, it can be more effective using a javascript based initialization - e.g. use different configs for inline+block code.</p>
<pre data-enlighter-language="html" data-enlighter-lineoffset="24">
<?php echo htmlspecialchars(extractContent('Example2-jsinit.html', 24, 66), ENT_HTML5); ?>
</pre>