<h2>Quickstart.html Code <small><a href="Quickstart.example.html">View file</a></small></h2>
<p>The following code provides a minimalistic example how to use EnlighterJS on your page, using the <strong>Metainit</strong> initialization method. This will be the best choice for most users.<br />
Metainit just invokes <code>EnlighterJS.Util.Helper()</code> on <code>domready</code> using metatag attributes as options.</p>
<p>For further information, please refer to the <a href="index.html">Documentation</a>.</p> 

<pre data-enlighter-language="html">
<?php echo htmlspecialchars(file_get_contents('Quickstart.html'), ENT_HTML5); ?>
</pre>

<h2>Classic Setup (Javascript Initialization - Quickstart-jsinit.html) <small><a href="Quickstart-jsinit.example.html">View file</a></small></h2>
<p>In some cases, it can be more effective using a manual javascript based initialization. </p>
<pre data-enlighter-language="html">
<?php echo htmlspecialchars(file_get_contents('Quickstart-jsinit.html'), ENT_HTML5); ?>
</pre>